### ISSUE TITLE
Reports Page: no margin on Android

### ISSUE THREAD

**Issue by sharmaine1028** [sharmaine1028/budgeking#36]
landing page (beige box)

**Comment by sharmaine1028** [comment]
no horizontal margin, perhaps can put some left padding first

**Comment by win-laeyee** [comment]
refer to new goal

**Comment by win-laeyee** [comment]
I cant see if the margin actually changes when I put left padding because on mine there is already a margin without adding leftPadding. maybe we can see when we're together on your Android emulator

**Comment by sharmaine1028** [comment]
Fixed by using Dimensions of device instead of fixed width
