### ISSUE TITLE
Signup and Login Page: Error when typing in Win Lae Yee in first name

### ISSUE THREAD

**Issue by winnnnnnnnnnn** [sharmaine1028/budgeking#53]
<img width="339" alt="Screenshot 2022-06-25 at 11 09 43 PM" src="https://user-images.githubusercontent.com/97848295/175938281-21ecb6c4-b314-476c-9587-a795031f5c9b.png">
<img width="327" alt="Screenshot 2022-06-25 at 11 11 47 PM" src="https://user-images.githubusercontent.com/97848295/175938306-6b8c3d1e-9d9c-4c5f-b8cc-c942265188ab.png">

**Comment by sharmaine1028** [comment]
@winnnnnnnnnnn Could you please try this again and let me know? Because I was unable to reproduce this error on my side. 
![image](https://user-images.githubusercontent.com/54767477/176068612-371dec51-8de2-4a5d-9e9e-108553bf6fb9.png)

**Comment by sharmaine1028** [comment]
Could possibly be due to database side, let me know if this problem still persists
