### ISSUE TITLE
Progress bar isn't filled up in Goal History even after user completes the goal + change sharing thingy

### ISSUE THREAD

**Issue by win-laeyee** [sharmaine1028/budgeking#88]
![Simulator Screen Shot - iPhone 12 Pro Max - 2022-07-20 at 17 30 27](https://user-images.githubusercontent.com/97848295/179948820-a2fc42c3-d6c4-43d3-b358-7f9e313d95c0.png)

**Comment by win-laeyee** [comment]
Also, change sharing thingy

**Comment by sharmaine1028** [comment]
@win-laeyee Do check if this error still occurs
