### ISSUE TITLE
Goals: Edit, save, delete box doesn't disappear after user is navigated to edit or save goal page

### ISSUE THREAD

**Issue by win-laeyee** [sharmaine1028/budgeking#89]
![Simulator Screen Shot - iPhone 12 Pro Max - 2022-07-20 at 17 33 09](https://user-images.githubusercontent.com/97848295/179949467-d2d96059-6a9f-479f-9be5-cce3a5c43c71.png)

**Comment by sharmaine1028** [comment]
@win-laeyee Do check if this error still occurs
